import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import Sidebar from '@/components/navbar/Sidebar';
import Profile from '@/components/navbar/Profile';
import Counter from '@/components/navbar/counter';
import { CustomerProvider } from '@/utility/store/customerContext'; // Import the customer provider

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Pooja Beverages',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomerProvider>
          <div>
            <div className="flex fixed top-0 right-0  left-0 bg-white  border-b shadow-sm justify-between items-center">
              <Sidebar />
              <Counter />
              <Profile />
            </div>
          </div>
          <div className="pt-14 overflow-hidden">{children}</div>
        </CustomerProvider>
        <Toaster />
      </body>
    </html>
  );
}
